[package]
name = "study-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
strum = "0.27.1"
strum_macros = "0.27.1"

[workspace]
resolver = "2"
members = [ "grammer", "hello-world" , "rpi"]

[workspace.dependencies]
rand = "0.9.1"
strum = "0.27.1"
strum_macros = "0.27.1"
